# Generated by Django 4.0.5 on 2022-06-30 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('info_contato', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('F', 'Finalizada')], default='A', max_length=1)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demanda.cidade')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demanda.uf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demanda.uf'),
        ),
    ]
